-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0

NDefines.NDiplomacy.ATTACKING_SOMEONE_CRUSADING_PIETY_COST = 100		-- vanilla: 40		-- Piety hit for attacking someone crusading
NDefines.NDiplomacy.PAPAL_INVEST_PIETY_COST_MULT = 0.75					-- vanilla: 0.5		-- The effect of Papal investiture on the piety cost of the special Papal actions
NDefines.NDiplomacy.SHORT_REIGN_YEARS_END = 10                      	-- vanilla: 9
NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 20                     	-- vanilla: 10
NDefines.NDiplomacy.DOW_ON_ALLY_PRESTIGE_COST = 100                 	-- vanilla: 50
NDefines.NDiplomacy.RELEASE_PRISONER_PIETY = 0                      	-- vanilla: 5
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_COUNT_MULT = 2.0					-- vanilla:	1.0		-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_DUKE_MULT = 2.0					-- vanilla:	1.0		-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.10			-- vanilla:	0.15	-- Extra Max Demesne Size from ruler and spouse stewardship
NDefines.NDiplomacy.VASSAL_LIMIT_DUKE_MULT = 5.0 						-- vanilla:	10.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_KING_MULT = 10.0 						-- vanilla:	20.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_EMPEROR_MULT = 20.0					-- vanilla:	30.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0					-- vanilla:	5.0		-- Extra Vassal Limit for Dukes with more than one Duchy
NDefines.NDiplomacy.VASSAL_LIMIT_DIPLOMACY_MULT = 0.3					-- vanilla:	0.3		-- Extra Vasal Limit from ruler and spouse diplomacy
NDefines.NDiplomacy.VASSAL_LIMIT_DECADENCE_MULTIPLIER = 0.50			-- vanilla:	0.25	-- Negative modifier multiplied with the current decadence.
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_DUKE_MULT = 5.0           	-- vanilla: 8.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_KING_MULT = 10.0          	-- vanilla: 15.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_EMPEROR_MULT = 20.0       	-- vanilla: 20.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0    	-- vanilla: 3.0
NDefines.NDiplomacy.ASSASSINATION_COST_RANK_MULT = 50					-- vanilla:	100		-- Additional cost for assassinations multiplied by rank (count = 1 emperor = 4). Also applies to children of rulers.
NDefines.NDiplomacy.INTER_MUSLIM_WAR_MONTHLY_PIETY_COST = 4				-- vanilla:	2		-- Monthly Piety cost for Muslims who are primary attackers against a ruler of the same religion (not civil wars)
NDefines.NDiplomacy.PAGAN_PEACE_MONTHS = 60								-- vanilla:	24		-- Months before the Peace Prestige loss kicks in for certain Pagan religions
NDefines.NDiplomacy.MIN_PREP_INV_TARGET_HOLDINGS = 12					-- vanilla:	9		-- The target must control at least this many holdings within the target kingdom to be a valid prepared invasion target
NDefines.NDiplomacy.MAX_PREP_INV_TARGET_HOLDINGS = 50					-- vanilla:	50		-- The target must control at the most this many holdings within the target kingdom to be a valid prepared invasion target
NDefines.NDiplomacy.BASE_REVOLT_CHANCE_MOD = 1000						-- vanilla:	250		-- Pre Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO.
NDefines.NDiplomacy.TOG_REVOLT_CHANCE_MOD = 200							-- vanilla:	100		-- Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO.
NDefines.NDiplomacy.DUKE_POWERFUL_VASSAL_COUNT = 3                  	-- vanilla: 4
NDefines.NDiplomacy.KING_POWERFUL_VASSAL_COUNT = 4                  	-- vanilla: 5
NDefines.NDiplomacy.EMPEROR_POWERFUL_VASSAL_COUNT = 5               	-- vanilla: 6
NDefines.NDiplomacy.IMPRISON_CHARACTER_INTERACTION_PIETY = 0        	-- vanilla: 10
NDefines.NDiplomacy.RELEASE_FROM_PRISON_INTERACTION_ENABLED = 1			-- vanilla:	1		-- Should this action be used at all?
NDefines.NDiplomacy.EXECUTE_IMPRISONED_INTERACTION_PIETY = 0        	-- vanilla: 20
NDefines.NDiplomacy.EXILE_IMPRISONED_INTERACTION_PIETY = 0          	-- vanilla: 10
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PIETY = 10	-- vanilla: 0
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0	-- vanilla: 1		-- Should this action be used at all?
NDefines.NDiplomacy.ASK_FOR_VASSALIZATION_INTERACTION_PRESTIGE = 25     -- vanilla: 0
NDefines.NDiplomacy.PREPARE_INVASION_INTERACTION_PRESTIGE = 1000        -- vanilla: 500
NDefines.NDiplomacy.ASK_TO_EMBARGO_INTERACTION_ENABLED = 0              -- vanilla: 1
NDefines.NDiplomacy.ASK_FOR_MONEY_INTERACTION_ENABLED = 0               -- vanilla: 1
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_MONEY = 100               -- vanilla: 0
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_PIETY = 250               -- vanilla: 75
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_THRESHOLD_FOR_NO = 75     -- vanilla: 0
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_THRESHOLD_FOR_YES = 175   -- vanilla: 0

NDefines.NCharacter.NEED_GUARDIAN_AT_AGE = 6                            -- vanilla: 6
NDefines.NCharacter.NON_AGGRESSION_PACT_BLOCKS_FACTIONS = 0             -- vanilla: 1
NDefines.NCharacter.WRONG_GOV_FORM_TAX_MOD = -0.5                       -- vanilla: -0.75
NDefines.NCharacter.WRONG_GOV_FORM_LEVY_MOD = -0.5                      -- vanilla: -0.75
NDefines.NCharacter.ASSIGN_ACTION_DAYS = 180							-- vanilla:	183		-- Days before a Councillor can be assigned a new job in a county
NDefines.NCharacter.RAISED_TROOPS_VASSAL_OPINION_DAYS = 73				-- vanilla:	61		-- After 73 days of having their troops raised vassals will get -1 opinion more of you
NDefines.NCharacter.MAX_GENERATED_TRAITS_FOR_HISTORICAL = 3				-- vanilla:	4		-- Generate random traits up this number for adult historical characters
NDefines.NCharacter.PORTRAIT_ADULT_MALE_AGE_THRESHOLD = 16				-- vanilla:	16		-- Male child to adult age portrait switch
NDefines.NCharacter.PORTRAIT_ADULT_FEMALE_AGE_THRESHOLD = 16			-- vanilla:	16		-- Female child to adult age portrait switch
NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 32						-- vanilla:	30		-- Middle age switch for character portraits
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_0 = 0						-- vanilla:	5		-- Natural deaths per decade out of 10000 people: Age 0-9
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_10 = 0						-- vanilla:	1		-- Natural deaths per decade out of 10000 people: Age 10-19
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_20 = 0						-- vanilla:	15		-- Natural deaths per decade out of 10000 people: Age 20-29
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_30 = 0						-- vanilla:	20		-- Natural deaths per decade out of 10000 people: Age 30-39
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_40 = 0						-- vanilla:	51		-- Natural deaths per decade out of 10000 people: Age 40-49
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_50 = 0						-- vanilla:	100		-- Natural deaths per decade out of 10000 people: Age 50-59
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_60 = 320					-- vanilla:	400		-- Natural deaths per decade out of 10000 people: Age 60-69
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_70 = 734					-- vanilla:	4400	-- Natural deaths per decade out of 10000 people: Age 70-79
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_80 = 1728					-- vanilla:	3500	-- Natural deaths per decade out of 10000 people: Age 80-90
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_90 = 4000					-- vanilla:	7000	-- Natural deaths per decade out of 10000 people: Age 90-99
NDefines.NCharacter.NATURAL_DEATH_CHANCE_AGE_100 = 8160					-- vanilla:	9000	-- Natural deaths per decade out of 10000 people: Age 100+
NDefines.NCharacter.NOT_SPOUSE_FERTILITY_MULT = 0.25					-- vanilla:	0.50	-- Applied to fertility when the two characters are not married
NDefines.NCharacter.INFANT_DEATH_CHANCE = 0								-- vanilla:	0.0		-- Chance of stillbirth / death at birth TODO: simulate 0.03% chance via event using "cancel_pregnancy"
NDefines.NCharacter.TRIBAL_EMPTY_HOLDING_TAX_MULTIPLIER = 0.5           -- vanilla: 0.5
NDefines.NCharacter.TRIBAL_EMPTY_HOLDING_LEVY_MULTIPLIER = 0.5          -- vanilla: 0.5
NDefines.NCharacter.TRIBAL_EMPTY_HOLDING_GARRISON_MULTIPLIER = 0.5      -- vanilla: 0.5
NDefines.NCharacter.AGE_CHILDHOOD_PULSE = 2								-- vanilla:	6		-- The childhood pulse events start from this age
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_STANDARD = 0.01		-- vanilla:	0.00	-- Chances that artifacts disappear on inheritance TODO: Rework this chance into on_action events
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_NO_HEIR = 0.1			-- vanilla:	0.5		-- Chances that artifacts disappear on inheritance when the dying character doesn't have an heir TODO: Rework this chance into on_action events

NDefines.NTitle.BARON_AS_VASSAL_PRESTIGE = 0.005                        -- vanilla: 0.025
NDefines.NTitle.COUNT_AS_VASSAL_PRESTIGE = 0.025                        -- vanilla: 0.1
NDefines.NTitle.DUKE_AS_VASSAL_PRESTIGE = 0.1                           -- vanilla: 0.4
NDefines.NTitle.KING_AS_VASSAL_PRESTIGE = 0.5                           -- vanilla: 1.6
NDefines.NTitle.EMPEROR_AS_VASSAL_PRESTIGE = 1.0						-- vanilla:	3.2		-- Impossible but needs to be here
NDefines.NTitle.BARON_TITLE_PRESTIGE = 0.05                             -- vanilla: 0.025
NDefines.NTitle.COUNT_TITLE_PRESTIGE = 0.075                            -- vanilla: 0.1
NDefines.NTitle.DUKE_TITLE_PRESTIGE = 0.1                               -- vanilla: 0.2
NDefines.NTitle.KING_TITLE_PRESTIGE = 0.5                               -- vanilla: 0.8
NDefines.NTitle.EMPEROR_TITLE_PRESTIGE = 1.0                            -- vanilla: 1.6
NDefines.NTitle.DUKE_GRANT_TO_CHURCH_PIETY = 100                        -- vanilla: 0
NDefines.NTitle.KING_GRANT_TO_CHURCH_PIETY = 250                        -- vanilla: 0
NDefines.NTitle.EMPEROR_GRANT_TO_CHURCH_PIETY = 500                     -- vanilla: 0
NDefines.NTitle.KING_GOLD_CREATION_COST = 500                           -- vanilla: 400
NDefines.NTitle.EMPEROR_GOLD_CREATION_COST = 1000                       -- vanilla: 600
NDefines.NTitle.KING_PIETY_CREATION_COST = 0                            -- vanilla: 200
NDefines.NTitle.EMPEROR_PIETY_CREATION_COST = 0                         -- vanilla: 400
NDefines.NTitle.KING_CREATION_PRESTIGE = 500                            -- vanilla: 400
NDefines.NTitle.EMPEROR_CREATION_PRESTIGE = 1000                        -- vanilla: 800
NDefines.NTitle.KING_DESTRUCTION_PRESTIGE_COST = 500                    -- vanilla: 400
NDefines.NTitle.EMPEROR_DESTRUCTION_PRESTIGE_COST = 1000                -- vanilla: 800
NDefines.NTitle.BARON_REVOKE_PRESTIGE_COST = 50                         -- vanilla: 25
NDefines.NTitle.COUNT_REVOKE_PRESTIGE_COST = 100                        -- vanilla: 50
NDefines.NTitle.DUKE_REVOKE_PRESTIGE_COST = 200                         -- vanilla: 100
NDefines.NTitle.KING_REVOKE_PRESTIGE_COST = 500                         -- vanilla: 200
NDefines.NTitle.EMPEROR_REVOKE_PRESTIGE_COST = 1000						-- vanilla:	400		-- Unused impossible
NDefines.NTitle.BARON_GRANT_DECADENCE_RED = 0.0025                      -- vanilla: 0.05
NDefines.NTitle.COUNT_GRANT_DECADENCE_RED = 0.01                        -- vanilla: 0.1
NDefines.NTitle.DUKE_GRANT_DECADENCE_RED = 0.02                         -- vanilla: 0.15
NDefines.NTitle.KING_GRANT_DECADENCE_RED = 0.05                         -- vanilla: 0.25
NDefines.NTitle.EMPEROR_GRANT_DECADENCE_RED = 0.1                       -- vanilla: 0.5
NDefines.NTitle.EMPIRE_DE_JURE_ASSIMILATION_YEARS = 50					-- vanilla:	100		-- Kingdoms under the de facto control of another empire will change de jure liege after this many years
NDefines.NTitle.TITULAR_TITLE_CREATION_COST_MULT = 1					-- vanilla:	2		-- Titular titles are more expensive to create
NDefines.NTitle.MAX_REPUBLIC_COUNTIES_IN_REALM = 0.2					-- vanilla:	0.1		-- 20% of a feudal realm is allowed to be under vassal republics (affects title grants)
NDefines.NTitle.MAX_THEOCRACY_COUNTIES_IN_REALM = 0.2					-- vanilla:	0.1		-- 20% of a feudal realm is allowed to be under vassal theocracies/bishoprics (affects title grants)

NDefines.NReligion.CREATE_ANTIPOPE_PRESTIGE_COST = 2000                 -- vanilla: 500
NDefines.NReligion.AUTHORITY_FROM_ANTIPOPE = 0.0						-- vanilla:	-0.3	-- Authority from each antipope

NDefines.NEconomy.DECADENCE_MODIFIER = 0.1								-- vanilla:	0.2		-- Maximum effect of decadence positive for low dec negative for high
NDefines.NEconomy.DECADENCE_PER_WEEK_OF_COMBAT = -0.01					-- vanilla:	-0.04	-- Decadence lost per 7 days of combat for each participant in the combat
NDefines.NEconomy.DECADENCE_PER_WEEK_OF_SIEGE = -0.0016					-- vanilla:	-0.008	-- Decadence lost per 7 days of siege for each participant in the siege
NDefines.NEconomy.MIN_TRADE_POSTS = 3									-- vanilla:	4		-- Minimum number of max trade posts per patrician
NDefines.NEconomy.PATRICIAN_CITY_TAX_MULT = 0.25						-- vanilla:	0.5		-- Patricians don't pay normal City Tax to their liege... (CFixedPoint64)
NDefines.NEconomy.OVER_MAX_DEMESNE_TAX_PENALTY = 0.33					-- vanilla:	0.20	-- Percent penalty per county over the limit
NDefines.NEconomy.TAX_TO_LOOT_MULTIPLIER = 0.5							-- vanilla:	1.0		-- Lootable gold per tax
NDefines.NEconomy.FORT_LOOT_DEFENCE_MULTIPLIER = 1.0					-- vanilla:	4.0		-- Loot protected gold per fortlevel
NDefines.NEconomy.LOOTABLE_GOLD_REGROWTH = 0.01							-- vanilla:	0.015	-- Percent of max lootable gold that regrows every month
NDefines.NEconomy.LOOT_PRESTIGE_MULT = 0.5								-- vanilla:	1.0		-- Whenever you gain loot you also get prestige related to the loot
NDefines.NEconomy.LOOT_EVERY_X_DAYS = 8									-- vanilla:	4		-- Loot every this many days
NDefines.NEconomy.BUILDING_COST_MULT = 0.5								-- vanilla:	0.5		-- Increases build cost of all buildings
NDefines.NEconomy.FORT_CONSUMED_IN_SETTLEMENT_CONTRUCTION = 0			-- vanilla:	1		-- If set to 1 then fort holdings are consumed by the construction of another holding in the province while giving a discount to the construction cost in return.

NDefines.NDecadence.BASE_EMPEROR_GAIN = 0.25                            -- vanilla: 0.1
NDefines.NDecadence.BASE_KING_GAIN = 0.18                               -- vanilla: 0.1
NDefines.NDecadence.BASE_DUKE_GAIN = 0.12                               -- vanilla: 0.1
NDefines.NDecadence.BASE_COUNT_GAIN = 0.10                              -- vanilla: 0.1
NDefines.NDecadence.BASE_BARON_GAIN = 0.08                              -- vanilla: 0.1
NDefines.NDecadence.BASE_UNLANDED_GAIN = 0.05                           -- vanilla: 0.1
NDefines.NDecadence.REALM_SIZE_MULTIPLIER = 0                           -- vanilla: 0.001
NDefines.NDecadence.DEMESNE_FRACTION_MULT_POS = 0                       -- vanilla: 0.5
NDefines.NDecadence.DEMESNE_FRACTION_MULT_NEG = 0                       -- vanilla: -0.8

NDefines.NNomad.MAX_POPULATION_EMPTY_HOLDING_MULTIPLIER = 1500			-- vanilla:	1000	-- Max population increase for each empty holding in provinces where the capital is also an empty holding
NDefines.NNomad.STARTING_HORDE_MAX_FRACTION = 1							-- vanilla:	0.80	-- The hordes will start with STARTING_HORDE_MAX_FRACTION of maximum subunits allowed by their manpower
NDefines.NNomad.UNITS_FOR_OCCUPATION = 50								-- vanilla:	100		-- Number of hostile units needing to stand on settlement-less nomad provinces to be considered occupied
NDefines.NNomad.CLAN_PRESTIGE_SCALE = 0.01								-- vanilla:	0.005	-- How fast the scale of the prestige opinion bonus/malus grows
NDefines.NNomad.PROVINCES_PER_CLAN = 4									-- vanilla:	5		-- Used to calculate if you have too many clans
NDefines.NNomad.MAX_CLANS = 12											-- vanilla:	9		-- The maximum amount of clans, regardless of realm size
NDefines.NNomad.TOO_MUCH_COMPETITION = 10								-- vanilla:	15		-- Opinion malus if you have too many clans
NDefines.NNomad.CLANS_WANT_MORE_LAND = 25								-- vanilla:	20		-- Opinion malus per province too many held

NDefines.NMilitary.MERCENARY_HIRE_COST_FACTOR = 0.2						-- vanilla:	0.1		-- Hire cost factor for mercenary units
NDefines.NMilitary.HOLY_ORDER_HIRE_COST_FACTOR = 0.5					-- vanilla:	0.25	-- Conversion of nominal gold cost to piety cost when hiring Holy Orders
NDefines.NMilitary.MERCENARY_HIRE_DISTANCE_THRESHOLD = 450				-- vanilla:	680		-- Mercs will not be available if the province of origin is more distant from your capital
NDefines.NMilitary.BATTLE_WARSCORE_DEFENDER_MULTIPLIER = 1.00			-- vanilla:	1.5		-- Defenders wins are multiplied with this value which also means they get more prestige for a win
NDefines.NMilitary.MIN_LEVY_RAISE_OPINION_THRESHOLD = -25				-- vanilla:	0		-- Below this opinion value you'll get the least amount of troops possible
NDefines.NMilitary.SIEGE_MORALE_LOSS = 0.4								-- vanilla:	0.5		-- Monthly morale loss in a siege
NDefines.NMilitary.SIEGE_WEALTH_MULTIPLIER = 0.75						-- vanilla:	1		-- Wealth gain/loss multiplier for sieges
NDefines.NMilitary.CAPITAL_WARSCORE_MULTIPLIER = 1.5					-- vanilla:	1		-- Warscore multiplier for capital(this is scaled with SETTLEMENT_WARSCORE_MULTIPLIER)
NDefines.NMilitary.SETTLEMENT_WARSCORE_MULTIPLIER = 0.5					-- vanilla:	0.3		-- Warscore worth for occupied private demesne
NDefines.NMilitary.VASSAL_SETTLEMENT_WARSCORE_MULTIPLIER = 0.5			-- vanilla:	0.3		-- Warscore worth for occupied vassals
NDefines.NMilitary.OVERRUN_RATIO = 10									-- vanilla:	25		-- Ratio needed for total extermination of enemy units
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS = 60						-- vanilla:	12		-- This and below are different modifier lengths applied to settlements upon conquest
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_RELIGION = 0     -- vanilla: 90
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_RELIGIONGROUP = 0-- vanilla: 180
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_CULTURE = 0      -- vanilla: 30
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_CULTUREGROUP = 0 -- vanilla: 120
NDefines.NMilitary.LIEGE_LEVY_SIZE_MULTIPLIER = 1.0						-- vanilla:	0.5		-- The Size of the liege levy will be the total troops in the vassal subrealm * this
NDefines.NMilitary.LIEGE_LEVY_COST_MULTIPLIER = 0.25					-- vanilla:	1.0		-- The vassal will pay regular maintenance * this for the liege levy
NDefines.NMilitary.LIGHT_INFANTRY_MORALE = 3                            -- vanilla: 2
NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = 1.5                     -- vanilla: 0.70
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_ATTACK = 1             -- vanilla: 1.25
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_ATTACK = 3                -- vanilla: 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 3               -- vanilla: 2
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_DEFENSE = 3            -- vanilla: 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_DEFENSE = 3               -- vanilla: 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_DEFENSE = 2              -- vanilla: 2.5
NDefines.NMilitary.HEAVY_INFANTRY_MORALE = 5                            -- vanilla: 4
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_ATTACK = 0.25          -- vanilla: 3
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_ATTACK = 6                -- vanilla: 6
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 2               -- vanilla: 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_DEFENSE = 5            -- vanilla: 3
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_DEFENSE = 4               -- vanilla: 4
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_DEFENSE = 2              -- vanilla: 4
NDefines.NMilitary.PIKEMEN_MORALE = 6                                   -- vanilla: 6
NDefines.NMilitary.PIKEMEN_MAINTENANCE = 3                              -- vanilla: 2.5
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_ATTACK = 0.1                  -- vanilla: 0.1
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_ATTACK = 5                       -- vanilla: 4.5
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 0.2                    -- vanilla: 0.2
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_DEFENSE = 4                   -- vanilla: 4
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_DEFENSE = 8                      -- vanilla: 4.5
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_DEFENSE = 1.5                   -- vanilla: 2
NDefines.NMilitary.LIGHT_CAVALRY_MORALE = 4                             -- vanilla: 1
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_ATTACK = 1.5            -- vanilla: 2
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_ATTACK = 4.5               -- vanilla: 3
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 15               -- vanilla: 6
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_DEFENSE = 5             -- vanilla: 4.5
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_DEFENSE = 3                -- vanilla: 3
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_DEFENSE = 8               -- vanilla: 4.5
NDefines.NMilitary.KNIGHTS_MORALE = 10                                  -- vanilla: 10
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_ATTACK = 0.5                  -- vanilla: 0.5
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_ATTACK = 10                      -- vanilla: 10
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 8                      -- vanilla: 4
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_DEFENSE = 8                   -- vanilla: 6
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_DEFENSE = 8                      -- vanilla: 6
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_DEFENSE = 4                     -- vanilla: 5
NDefines.NMilitary.ARCHERS_MORALE = 1                                   -- vanilla: 1
NDefines.NMilitary.ARCHERS_MAINTENANCE = 1.5                            -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_ATTACK = 5                    -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_MELEE_ATTACK = 1                       -- vanilla: 1
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_ATTACK = 2                      -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_DEFENSE = 3                   -- vanilla: 1.5
NDefines.NMilitary.ARCHERS_PHASE_MELEE_DEFENSE = 2                      -- vanilla: 1.5
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_DEFENSE = 2                     -- vanilla: 2.25
NDefines.NMilitary.SPECIAL_TROOPS_MORALE = 5                            -- vanilla: 5
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_SKIRMISH_ATTACK = 4             -- vanilla: 4
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_MELEE_ATTACK = 3                -- vanilla: 3
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_ATTACK = 7               -- vanilla: 7
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_SKIRMISH_DEFENSE = 4            -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_MELEE_DEFENSE = 4               -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_DEFENSE = 7              -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_GRAPHICAL_FACTOR = 2.0                -- vanilla: 2
NDefines.NMilitary.GALLEYS_MAINTENANCE = 50                             -- vanilla: 300
NDefines.NMilitary.MAX_RIVER_MOVEMENT_FORT_LEVEL = 15.0                 -- vanilla: 10
NDefines.NMilitary.OUTSIDE_LIEGE_LEVY_MULT = 0.35						-- vanilla:	0.25	-- Multiplier to liege levies outside all capital regions

NDefines.NDisease.INFECTION_CHANCE_MODIFIER_TRADEPOST = 0.03            -- vanilla: 0.05
NDefines.NDisease.INFECTION_CHANCE_MODIFIER_TRADEROUTE = 0.03           -- vanilla: 0.5

NDefines.NGraphics.CITY_SPRAWL_AMOUNT = 0.75							-- vanilla:	1		-- Size of cities, higher gives larger cities

NDefines.NTechnology.IDEAL_YEAR_AHEAD_PENALTY_INVEST = 0.4				-- vanilla:	0.6		-- Percent increase in cost pre level ahead of ideal date

NDefines.NAI.DOW_AGGRESSION_FACTOR = 1.0								-- vanilla:	0.66	-- General aggressiveness declarations of war
NDefines.NAI.MARRIAGE_AI_PRESTIGE_VALUE = 0.67							-- vanilla:	0.33	-- Multiplier for how highly AI values prestige when arranging marriages and evaluating marriage offers
NDefines.NAI.MAX_EMPIRE_TITLES_TO_CREATE = 1							-- vanilla:	0		-- AI will not seek to create/usurp more Empire-level titles than this (0 for unlimited)
NDefines.NAI.AI_EMPEROR_CREATES_KINGDOMS = 1							-- vanilla:	0		-- If set to 1 AI Emperors will create King-level titles
NDefines.NAI.AI_ALWAYS_CREATES_DUCHIES = 1								-- vanilla:	0		-- If set to 1 AI will always create Duchy titles even if it has Gavelkind etc
NDefines.NAI.AI_ASSAULT_RATIO = 12										-- vanilla:	10		-- AI will launch assaults at this ratio of attackers to defenders
NDefines.NAI.DESIRED_CONSORTS = 3										-- vanilla:	0		-- AI will always want at least this many concubines if they lack sons
NDefines.NAI.RAID_AGGRESSION = 24										-- vanilla:	18		-- General frequency of raids. A LOWER number means more often!

NDefines.NEndGame.DYN1_SCORE = 50000                                    -- vanilla: 100000
NDefines.NEndGame.DYN2_SCORE = 45000                                    -- vanilla: 90000
NDefines.NEndGame.DYN3_SCORE = 40000                                    -- vanilla: 80000
NDefines.NEndGame.DYN4_SCORE = 35000                                    -- vanilla: 70000
NDefines.NEndGame.DYN5_SCORE = 30000                                    -- vanilla: 60000
NDefines.NEndGame.DYN6_SCORE = 25000                                    -- vanilla: 50000
NDefines.NEndGame.DYN6_ID = 171                                         -- vanilla: 634
NDefines.NEndGame.DYN7_SCORE = 20000                                    -- vanilla: 40000
NDefines.NEndGame.DYN8_SCORE = 15000                                    -- vanilla: 30000
NDefines.NEndGame.DYN9_SCORE = 10000                                    -- vanilla: 20000
NDefines.NEndGame.DYN10_SCORE = 7500                                    -- vanilla: 15000
NDefines.NEndGame.DYN11_SCORE = 5000                                    -- vanilla: 10000
NDefines.NEndGame.DYN12_SCORE = 3000                                    -- vanilla: 7500
NDefines.NEndGame.DYN13_SCORE = 2000                                    -- vanilla: 5000
NDefines.NEndGame.DYN14_SCORE = 1000                                    -- vanilla: 2000
NDefines.NEndGame.DYN15_SCORE = 500                                     -- vanilla: 1000

NDefines.NRulerDesigner.COST_ATTRIB = 0.5                               -- vanilla: 1.0
NDefines.NRulerDesigner.COST_SON = 2.0                                  -- vanilla: 3.0
NDefines.NRulerDesigner.COST_DAUGHTER = 1.0                             -- vanilla: 2.0
NDefines.NRulerDesigner.COST_MARRIED = 0                                -- vanilla: 2.0
NDefines.NRulerDesigner.COST_FERTILITY = 10.0                           -- vanilla: 20.0
NDefines.NRulerDesigner.COST_HEALTH = 5.0                               -- vanilla: 10.0
NDefines.NRulerDesigner.COST_COMBAT_RATING = 1.0                        -- vanilla: 0.0
NDefines.NRulerDesigner.COST_MONTHLY_PRESTIGE = 5.0                     -- vanilla: 10.0
NDefines.NRulerDesigner.COST_MONTHLY_PIETY = 5.0                        -- vanilla: 20.0
NDefines.NRulerDesigner.COST_MONTHLY_WEALTH = 5.0                       -- vanilla: 10.0
NDefines.NRulerDesigner.COST_GLOBAL_TAX = 25.0                          -- vanilla: 50.0
NDefines.NRulerDesigner.COST_CHURCH_OPINION = 0.25                      -- vanilla: 0.5
NDefines.NRulerDesigner.COST_SPOUCE_OPINION = 0.25                      -- vanilla: 0.5
NDefines.NRulerDesigner.COST_SEXAPPEAL_OPINION = 0.25                   -- vanilla: 0.5
NDefines.NRulerDesigner.COST_DYNASTY_OPINION = 0.25                     -- vanilla: 0.5
NDefines.NRulerDesigner.COST_VASSAL_OPINION = 0.5                       -- vanilla: 1.0
NDefines.NRulerDesigner.COST_OPPOSITE_TRAIT_OPINION = 0                 -- vanilla: 0.5
NDefines.NRulerDesigner.COST_SAME_TRAIT_OPINION = 0                     -- vanilla: 0.5
NDefines.NRulerDesigner.COST_SAME_RELIGION_OPINION = 0.25               -- vanilla: 0.5
NDefines.NRulerDesigner.COST_TRIBAL_OPINION = 0.25                      -- vanilla: 0.0
NDefines.NRulerDesigner.COST_UNREFORMED_TRIBAL_OPINION = 0.25           -- vanilla: 0.0
NDefines.NRulerDesigner.COST_GENERAL_OPINION = 0.5                      -- vanilla: 1.0
NDefines.NRulerDesigner.COST_MORALE_OFFENCE = 25.0                      -- vanilla: 50.0
NDefines.NRulerDesigner.COST_MORALE_DEFENCE = 25.0                      -- vanilla: 50.0
NDefines.NRulerDesigner.COST_DEFENCE = 25.0                             -- vanilla: 50.0

--Changes to Infamy and Coalitions
NDefines.NDiplomacy.DEFENSIVE_PACT_THREAT_LIMIT = 0.15					-- vanilla:	0.05	-- The amount of threat that is needed for a defensive pact to be created
NDefines.NDiplomacy.DEFENSIVE_PACT_MAX_RANGE = 300						-- vanilla:	400		-- At 100% threat characters are able to join defensive pacts against targets of this distance
NDefines.NDiplomacy.MAX_INFAMY_GAIN = 20.0								-- vanilla:	50		-- This is the max infamy gained from a single source
NDefines.NInfamy.REALM_SIZE_GROWTH_MODIFIER = 5.0						-- vanilla:	0.125	-- The bigger you are, the more dangerous you are, modifier for when nation is shrinking
NDefines.NInfamy.INHERITANCE_CHANGE_VALUE = 0							-- vanilla:	0.15	-- How much base value for realm growth/shrink is worth when inheriting titles.
NDefines.NInfamy.VASSAL_CHANGE_VALUE = 0	 							-- vanilla:	0.3		-- How much base value for realm growth/shrink is worth when inheriting titles.
NDefines.NInfamy.MIN_INFAMY_DECAY = 0.15								-- vanilla:	0.21	-- The minimum infamy decay regardless of troop strength.
NDefines.NInfamy.MAX_INFAMY_DECAY = 0.30								-- vanilla:	0.1		-- The maximum infamy decay regardless of troop strength.
NDefines.NInfamy.MAX_INFAMY_PER_WAR_PROVINCE = 4.0						-- vanilla:	12		-- A single province taken in war can give at most this much threat
NDefines.NInfamy.MIN_INFAMY_PER_WAR_PROVINCE = 1.0						-- vanilla:	5		-- A single province taken in war can give at most this much threat

--Reduce Effectiveness of Shattered Retreat
NDefines.NMilitary.SHATTERED_RETREAT_MOVEMENT_MULTIPLIER = 2.2          -- vanilla: 1.3
NDefines.NMilitary.SHATTERED_RETREAT_MORALE_MULTIPLIER = 1.0            -- vanilla: 1.5
NDefines.NMilitary.SHATTERED_RETREAT_PREFERRED_PROVINCES = 2            -- vanilla: 4
NDefines.NMilitary.SHATTERED_RETREAT_MAX_PROVINCES = 5                  -- vanilla: 10