-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NMilitary.MERCENARY_HIRE_COST_FACTOR = 0.2						-- vanilla:	0.1		-- Hire cost factor for mercenary units
NDefines.NMilitary.HOLY_ORDER_HIRE_COST_FACTOR = 0.5					-- vanilla:	0.25	-- Conversion of nominal gold cost to piety cost when hiring Holy Orders
NDefines.NMilitary.MERCENARY_HIRE_DISTANCE_THRESHOLD = 450				-- vanilla:	680		-- Mercs will not be available if the province of origin is more distant from your capital
NDefines.NMilitary.BATTLE_WARSCORE_DEFENDER_MULTIPLIER = 1.00			-- vanilla:	1.5		-- Defenders wins are multiplied with this value which also means they get more prestige for a win
NDefines.NMilitary.MIN_LEVY_RAISE_OPINION_THRESHOLD = -25				-- vanilla:	0		-- Below this opinion value you'll get the least amount of troops possible
NDefines.NMilitary.SIEGE_MORALE_LOSS = 0.4								-- vanilla:	0.5		-- Monthly morale loss in a siege
NDefines.NMilitary.SIEGE_WEALTH_MULTIPLIER = 0.75						-- vanilla:	1		-- Wealth gain/loss multiplier for sieges
NDefines.NMilitary.CAPITAL_WARSCORE_MULTIPLIER = 1.5					-- vanilla:	1		-- Warscore multiplier for capital(this is scaled with SETTLEMENT_WARSCORE_MULTIPLIER)
NDefines.NMilitary.SETTLEMENT_WARSCORE_MULTIPLIER = 0.5					-- vanilla:	0.3		-- Warscore worth for occupied private demesne
NDefines.NMilitary.VASSAL_SETTLEMENT_WARSCORE_MULTIPLIER = 0.5			-- vanilla:	0.3		-- Warscore worth for occupied vassals
NDefines.NMilitary.OVERRUN_RATIO = 10									-- vanilla:	25		-- Ratio needed for total extermination of enemy units
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS = 60						-- vanilla:	12		-- This and below are different modifier lengths applied to settlements upon conquest
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_RELIGION = 0     -- vanilla: 90
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_RELIGIONGROUP = 0-- vanilla: 180
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_CULTURE = 0      -- vanilla: 30
NDefines.NMilitary.OCCUPATION_PENALTY_MONTHS_DIFFERENT_CULTUREGROUP = 0 -- vanilla: 120
NDefines.NMilitary.LIEGE_LEVY_SIZE_MULTIPLIER = 1.0						-- vanilla:	0.5		-- The Size of the liege levy will be the total troops in the vassal subrealm * this
NDefines.NMilitary.LIEGE_LEVY_COST_MULTIPLIER = 0.25					-- vanilla:	1.0		-- The vassal will pay regular maintenance * this for the liege levy
NDefines.NMilitary.LIGHT_INFANTRY_MORALE = 3                            -- vanilla: 2
NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = 1.5                     -- vanilla: 0.70
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_ATTACK = 1             -- vanilla: 1.25
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_ATTACK = 3                -- vanilla: 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 3               -- vanilla: 2
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_DEFENSE = 3            -- vanilla: 3
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_DEFENSE = 3               -- vanilla: 1
NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_DEFENSE = 2              -- vanilla: 2.5
NDefines.NMilitary.HEAVY_INFANTRY_MORALE = 5                            -- vanilla: 4
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_ATTACK = 0.25          -- vanilla: 3
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_ATTACK = 6                -- vanilla: 6
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 2               -- vanilla: 1
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_DEFENSE = 5            -- vanilla: 3
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_DEFENSE = 4               -- vanilla: 4
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_DEFENSE = 2              -- vanilla: 4
NDefines.NMilitary.PIKEMEN_MORALE = 6                                   -- vanilla: 6
NDefines.NMilitary.PIKEMEN_MAINTENANCE = 3                              -- vanilla: 2.5
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_ATTACK = 0.1                  -- vanilla: 0.1
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_ATTACK = 5                       -- vanilla: 4.5
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 0.2                    -- vanilla: 0.2
NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_DEFENSE = 4                   -- vanilla: 4
NDefines.NMilitary.PIKEMEN_PHASE_MELEE_DEFENSE = 8                      -- vanilla: 4.5
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_DEFENSE = 1.5                   -- vanilla: 2
NDefines.NMilitary.LIGHT_CAVALRY_MORALE = 4                             -- vanilla: 1
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_ATTACK = 1.5            -- vanilla: 2
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_ATTACK = 4.5               -- vanilla: 3
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 15               -- vanilla: 6
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_DEFENSE = 5             -- vanilla: 4.5
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_DEFENSE = 3                -- vanilla: 3
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_DEFENSE = 8               -- vanilla: 4.5
NDefines.NMilitary.KNIGHTS_MORALE = 10                                  -- vanilla: 10
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_ATTACK = 0.5                  -- vanilla: 0.5
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_ATTACK = 10                      -- vanilla: 10
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 8                      -- vanilla: 4
NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_DEFENSE = 8                   -- vanilla: 6
NDefines.NMilitary.KNIGHTS_PHASE_MELEE_DEFENSE = 8                      -- vanilla: 6
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_DEFENSE = 4                     -- vanilla: 5
NDefines.NMilitary.ARCHERS_MORALE = 1                                   -- vanilla: 1
NDefines.NMilitary.ARCHERS_MAINTENANCE = 1.5                            -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_ATTACK = 5                    -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_MELEE_ATTACK = 1                       -- vanilla: 1
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_ATTACK = 2                      -- vanilla: 2
NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_DEFENSE = 3                   -- vanilla: 1.5
NDefines.NMilitary.ARCHERS_PHASE_MELEE_DEFENSE = 2                      -- vanilla: 1.5
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_DEFENSE = 2                     -- vanilla: 2.25
NDefines.NMilitary.SPECIAL_TROOPS_MORALE = 5                            -- vanilla: 5
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_SKIRMISH_ATTACK = 4             -- vanilla: 4
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_MELEE_ATTACK = 3                -- vanilla: 3
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_ATTACK = 7               -- vanilla: 7
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_SKIRMISH_DEFENSE = 4            -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_MELEE_DEFENSE = 4               -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_DEFENSE = 7              -- vanilla: 1
NDefines.NMilitary.SPECIAL_TROOPS_GRAPHICAL_FACTOR = 2.0                -- vanilla: 2
NDefines.NMilitary.GALLEYS_MAINTENANCE = 50                             -- vanilla: 300
NDefines.NMilitary.MAX_RIVER_MOVEMENT_FORT_LEVEL = 15.0                 -- vanilla: 10
NDefines.NMilitary.OUTSIDE_LIEGE_LEVY_MULT = 0.35						-- vanilla:	0.25	-- Multiplier to liege levies outside all capital regions
--Reduce Effectiveness of Shattered Retreat
NDefines.NMilitary.SHATTERED_RETREAT_MOVEMENT_MULTIPLIER = 2.2          -- vanilla: 1.3
NDefines.NMilitary.SHATTERED_RETREAT_MORALE_MULTIPLIER = 1.0            -- vanilla: 1.5
NDefines.NMilitary.SHATTERED_RETREAT_PREFERRED_PROVINCES = 2            -- vanilla: 4
NDefines.NMilitary.SHATTERED_RETREAT_MAX_PROVINCES = 5                  -- vanilla: 10