--Reduce Effectiveness of Shattered Retreat
NDefines.NMilitary.SHATTERED_RETREAT_MOVEMENT_MULTIPLIER = 1.1
NDefines.NMilitary.SHATTERED_RETREAT_MORALE_MULTIPLIER = 1.0
NDefines.NMilitary.SHATTERED_RETREAT_PREFERRED_PROVINCES = 2
NDefines.NMilitary.SHATTERED_RETREAT_MAX_PROVINCES = 5
