-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NDiplomacy.ATTACKING_SOMEONE_CRUSADING_PIETY_COST = 100		-- vanilla: 40		-- Piety hit for attacking someone crusading
NDefines.NDiplomacy.PAPAL_INVEST_PIETY_COST_MULT = 0.75					-- vanilla: 0.5		-- The effect of Papal investiture on the piety cost of the special Papal actions
NDefines.NDiplomacy.SHORT_REIGN_YEARS_END = 10                      	-- vanilla: 9
NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 20                     	-- vanilla: 10
NDefines.NDiplomacy.DOW_ON_ALLY_PRESTIGE_COST = 100                 	-- vanilla: 50
NDefines.NDiplomacy.RELEASE_PRISONER_PIETY = 0                      	-- vanilla: 5
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_COUNT_MULT = 2.0					-- vanilla:	1.0		-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_DUKE_MULT = 2.0					-- vanilla:	1.0		-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.10			-- vanilla:	0.15	-- Extra Max Demesne Size from ruler and spouse stewardship
NDefines.NDiplomacy.VASSAL_LIMIT_DUKE_MULT = 5.0 						-- vanilla:	10.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_KING_MULT = 10.0 						-- vanilla:	20.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_EMPEROR_MULT = 20.0					-- vanilla:	30.0	-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0					-- vanilla:	5.0		-- Extra Vassal Limit for Dukes with more than one Duchy
NDefines.NDiplomacy.VASSAL_LIMIT_DIPLOMACY_MULT = 0.3					-- vanilla:	0.3		-- Extra Vasal Limit from ruler and spouse diplomacy
NDefines.NDiplomacy.VASSAL_LIMIT_DECADENCE_MULTIPLIER = 0.50			-- vanilla:	0.25	-- Negative modifier multiplied with the current decadence.
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_DUKE_MULT = 5.0           	-- vanilla: 8.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_KING_MULT = 10.0          	-- vanilla: 15.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_EMPEROR_MULT = 20.0       	-- vanilla: 20.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0    	-- vanilla: 3.0
NDefines.NDiplomacy.ASSASSINATION_COST_RANK_MULT = 50					-- vanilla:	100		-- Additional cost for assassinations multiplied by rank (count = 1 emperor = 4). Also applies to children of rulers.
NDefines.NDiplomacy.INTER_MUSLIM_WAR_MONTHLY_PIETY_COST = 4				-- vanilla:	2		-- Monthly Piety cost for Muslims who are primary attackers against a ruler of the same religion (not civil wars)
NDefines.NDiplomacy.PAGAN_PEACE_MONTHS = 60								-- vanilla:	24		-- Months before the Peace Prestige loss kicks in for certain Pagan religions
NDefines.NDiplomacy.MIN_PREP_INV_TARGET_HOLDINGS = 12					-- vanilla:	9		-- The target must control at least this many holdings within the target kingdom to be a valid prepared invasion target
NDefines.NDiplomacy.MAX_PREP_INV_TARGET_HOLDINGS = 50					-- vanilla:	50		-- The target must control at the most this many holdings within the target kingdom to be a valid prepared invasion target
NDefines.NDiplomacy.BASE_REVOLT_CHANCE_MOD = 1000						-- vanilla:	250		-- Pre Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO.
NDefines.NDiplomacy.TOG_REVOLT_CHANCE_MOD = 200							-- vanilla:	100		-- Old Gods rebel spawn chance modifier (fires on_rebel_revolt) : lower means fewer revolts. MUST NOT BE ZERO.
NDefines.NDiplomacy.DUKE_POWERFUL_VASSAL_COUNT = 3                  	-- vanilla: 4
NDefines.NDiplomacy.KING_POWERFUL_VASSAL_COUNT = 4                  	-- vanilla: 5
NDefines.NDiplomacy.EMPEROR_POWERFUL_VASSAL_COUNT = 5               	-- vanilla: 6
NDefines.NDiplomacy.IMPRISON_CHARACTER_INTERACTION_PIETY = 0        	-- vanilla: 10
NDefines.NDiplomacy.RELEASE_FROM_PRISON_INTERACTION_ENABLED = 1			-- vanilla:	1		-- Should this action be used at all?
NDefines.NDiplomacy.EXECUTE_IMPRISONED_INTERACTION_PIETY = 0        	-- vanilla: 20
NDefines.NDiplomacy.EXILE_IMPRISONED_INTERACTION_PIETY = 0          	-- vanilla: 10
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PIETY = 10	-- vanilla: 0
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0	-- vanilla: 1		-- Should this action be used at all?
NDefines.NDiplomacy.ASK_FOR_VASSALIZATION_INTERACTION_PRESTIGE = 25     -- vanilla: 0
NDefines.NDiplomacy.PREPARE_INVASION_INTERACTION_PRESTIGE = 1000        -- vanilla: 500
NDefines.NDiplomacy.ASK_TO_EMBARGO_INTERACTION_ENABLED = 0              -- vanilla: 1
NDefines.NDiplomacy.ASK_FOR_MONEY_INTERACTION_ENABLED = 0               -- vanilla: 1
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_MONEY = 100               -- vanilla: 0
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_PIETY = 250               -- vanilla: 75
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_THRESHOLD_FOR_NO = 75     -- vanilla: 0
NDefines.NDiplomacy.ASK_FOR_CLAIM_INTERACTION_THRESHOLD_FOR_YES = 175   -- vanilla: 0
NDefines.NDiplomacy.DEFENSIVE_PACT_THREAT_LIMIT = 0.15					-- vanilla:	0.05	-- The amount of threat that is needed for a defensive pact to be created
NDefines.NDiplomacy.DEFENSIVE_PACT_MAX_RANGE = 300						-- vanilla:	400		-- At 100% threat characters are able to join defensive pacts against targets of this distance
NDefines.NDiplomacy.MAX_INFAMY_GAIN = 20.0								-- vanilla:	50		-- This is the max infamy gained from a single source