-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NTitle.BARON_AS_VASSAL_PRESTIGE = 0.005                        -- vanilla: 0.025
NDefines.NTitle.COUNT_AS_VASSAL_PRESTIGE = 0.025                        -- vanilla: 0.1
NDefines.NTitle.DUKE_AS_VASSAL_PRESTIGE = 0.1                           -- vanilla: 0.4
NDefines.NTitle.KING_AS_VASSAL_PRESTIGE = 0.5                           -- vanilla: 1.6
NDefines.NTitle.EMPEROR_AS_VASSAL_PRESTIGE = 1.0						-- vanilla:	3.2		-- Impossible but needs to be here
NDefines.NTitle.BARON_TITLE_PRESTIGE = 0.05                             -- vanilla: 0.025
NDefines.NTitle.COUNT_TITLE_PRESTIGE = 0.075                            -- vanilla: 0.1
NDefines.NTitle.DUKE_TITLE_PRESTIGE = 0.1                               -- vanilla: 0.2
NDefines.NTitle.KING_TITLE_PRESTIGE = 0.5                               -- vanilla: 0.8
NDefines.NTitle.EMPEROR_TITLE_PRESTIGE = 1.0                            -- vanilla: 1.6
NDefines.NTitle.DUKE_GRANT_TO_CHURCH_PIETY = 100                        -- vanilla: 0
NDefines.NTitle.KING_GRANT_TO_CHURCH_PIETY = 250                        -- vanilla: 0
NDefines.NTitle.EMPEROR_GRANT_TO_CHURCH_PIETY = 500                     -- vanilla: 0
NDefines.NTitle.KING_GOLD_CREATION_COST = 500                           -- vanilla: 400
NDefines.NTitle.EMPEROR_GOLD_CREATION_COST = 1000                       -- vanilla: 600
NDefines.NTitle.KING_PIETY_CREATION_COST = 0                            -- vanilla: 200
NDefines.NTitle.EMPEROR_PIETY_CREATION_COST = 0                         -- vanilla: 400
NDefines.NTitle.KING_CREATION_PRESTIGE = 500                            -- vanilla: 400
NDefines.NTitle.EMPEROR_CREATION_PRESTIGE = 1000                        -- vanilla: 800
NDefines.NTitle.KING_DESTRUCTION_PRESTIGE_COST = 500                    -- vanilla: 400
NDefines.NTitle.EMPEROR_DESTRUCTION_PRESTIGE_COST = 1000                -- vanilla: 800
NDefines.NTitle.BARON_REVOKE_PRESTIGE_COST = 50                         -- vanilla: 25
NDefines.NTitle.COUNT_REVOKE_PRESTIGE_COST = 100                        -- vanilla: 50
NDefines.NTitle.DUKE_REVOKE_PRESTIGE_COST = 200                         -- vanilla: 100
NDefines.NTitle.KING_REVOKE_PRESTIGE_COST = 500                         -- vanilla: 200
NDefines.NTitle.EMPEROR_REVOKE_PRESTIGE_COST = 1000						-- vanilla:	400		-- Unused impossible
NDefines.NTitle.BARON_GRANT_DECADENCE_RED = 0.0025                      -- vanilla: 0.05
NDefines.NTitle.COUNT_GRANT_DECADENCE_RED = 0.01                        -- vanilla: 0.1
NDefines.NTitle.DUKE_GRANT_DECADENCE_RED = 0.02                         -- vanilla: 0.15
NDefines.NTitle.KING_GRANT_DECADENCE_RED = 0.05                         -- vanilla: 0.25
NDefines.NTitle.EMPEROR_GRANT_DECADENCE_RED = 0.1                       -- vanilla: 0.5
NDefines.NTitle.EMPIRE_DE_JURE_ASSIMILATION_YEARS = 50					-- vanilla:	100		-- Kingdoms under the de facto control of another empire will change de jure liege after this many years
NDefines.NTitle.TITULAR_TITLE_CREATION_COST_MULT = 1					-- vanilla:	2		-- Titular titles are more expensive to create
NDefines.NTitle.MAX_REPUBLIC_COUNTIES_IN_REALM = 0.2					-- vanilla:	0.1		-- 20% of a feudal realm is allowed to be under vassal republics (affects title grants)
NDefines.NTitle.MAX_THEOCRACY_COUNTIES_IN_REALM = 0.2					-- vanilla:	0.1		-- 20% of a feudal realm is allowed to be under vassal theocracies/bishoprics (affects title grants)